# Generated by Django 5.0.4 on 2024-11-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_pedido_cliente_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PREP', 'En preparación'), ('LIST', 'Listo para entrega'), ('ENTR', 'Entregado')], default='PREP', max_length=4),
        ),
    ]
